sonar.projectKey=myproject
sonar.projectName=My Project
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.login=sqa_af9234fbb7dd1a04ab0b368909209caef5dcd2ff
sonar.host.url=http://43.204.232.176:9000
